const token = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: token("ink"),
        rice: token("rice"),
        paper: token("paper"),
        sakura: token("sakura"),
        matcha: token("matcha"),
        sora: token("sora"),
        yuzu: token("yuzu"),
        sumire: token("sumire"),
        coral: token("sakura"),
        indigo: token("sumire"),
        sun: token("yuzu"),
        sky: token("sky"),
      },
      fontFamily: {
        sans: [
          '"Microsoft YaHei UI"',
          '"Microsoft YaHei"',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Noto Sans SC"',
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "sans-serif",
        ],
        display: [
          '"Microsoft YaHei UI"',
          '"Microsoft YaHei"',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Noto Sans SC"',
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "sans-serif",
        ],
        japanese: [
          '"Yu Gothic UI"',
          '"Yu Gothic"',
          '"Hiragino Sans"',
          '"Hiragino Kaku Gothic ProN"',
          "Meiryo",
          '"Noto Sans JP"',
          '"Microsoft YaHei UI"',
          '"Microsoft YaHei"',
          "sans-serif",
        ],
        reading: [
          '"Noto Sans JP"',
          '"Segoe UI"',
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
      },
      boxShadow: {
        soft: "0 12px 28px rgba(34, 38, 34, 0.08)",
        card: "0 8px 18px rgba(34, 38, 34, 0.06)",
        pop: "0 8px 0 rgba(34, 38, 34, 0.035), 0 14px 24px rgba(34, 38, 34, 0.07)",
      },
      opacity: {
        2: "0.02",
        6: "0.06",
        8: "0.08",
        12: "0.12",
        14: "0.14",
        15: "0.15",
        16: "0.16",
        18: "0.18",
        22: "0.22",
        24: "0.24",
        28: "0.28",
        35: "0.35",
        38: "0.38",
        42: "0.42",
        45: "0.45",
        48: "0.48",
        52: "0.52",
        54: "0.54",
        55: "0.55",
        58: "0.58",
        62: "0.62",
        65: "0.65",
        66: "0.66",
        68: "0.68",
        72: "0.72",
        76: "0.76",
        78: "0.78",
        82: "0.82",
        85: "0.85",
        88: "0.88",
        92: "0.92",
        94: "0.94",
        96: "0.96",
      },
    },
  },
  plugins: [],
};
